default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  database: production
  encoding: unicode
  adapter: postgresql
  pool: 5
  host: <%=ENV["DATABASE_HOST"]%>
